lib/node_monitor_web/router.ex
defmodule NodeMonitorWeb.Router do
  use NodeMonitorWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", NodeMonitorWeb do
    pipe_through :browser

    # landing pages
    get "/", NodesController, :all_nodes
    get "/overview", NodesController, :overview
    get "/map", NodesController, :map

    # node detail pages
    get "/nodes/:id", NodesController, :show
  end
end

lib/node_monitor/nodes/node.ex
defmodule NodeMonitor.Nodes.Node do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key{:id, :string, autogenerate: false}
  schema "nodes" do
    field :vsn,             :string,          default: nil
    field :lon,             :float,           default: nil
    field :lat,             :float,           default: nil
    field :address,         :string,          default: nil
    field :description,     :string,          default: nil
    field :start_timestamp, :naive_datetime,  default: nil
    field :end_timestamp,   :naive_datetime,  default: nil
  end

  @attrs ~w| id vsn lon lat address description start_timestamp end_timestamp |a
  @reqd ~w| id vsn |a

  @doc false
  def changeset(node, params) do
    node
    |> cast(params, @attrs)
    |> validate_required(@reqd)
    |> unique_constraint(:id, name: :nodes_pkey)
  end
end

lib/node_monitor/nodes/nodes.ex
defmodule NodeMonitor.Nodes do
  require Logger
  import Ecto.Query
  alias NimbleCSV.RFC4180, as: CSV
  alias NodeMonitor.Nodes.Node
  alias NodeMonitor.Repo

  @doc "Creates a base queryset for live nodes"
  @spec list_nodes() :: Ecto.Queryable.t()
  def list_nodes, do: from n in Node, where: is_nil(n.end_timestamp)

  @doc """
  Downloads all the projects' recent tarballs and processes their
  nodes.csv files to create/update nodes in the database.
  """
  @spec load_recent_tarballs() :: :ok
  def load_recent_tarballs do
    tarball_paths =
      # ~w| NUCWR-MUGS GASP Waggle_Dronebears LinkNYC AoT_Seattle AoT_Portland AoT_NIU AoT_Syracuse AoT_Detroit Waggle_Others AoT_UNC AoT_UW AoT_Chicago AoT_Stanford AoT_Denver Waggle_Tokyo |
      ~w| AoT_Chicago |
      |> Enum.map(&("https://www.mcs.anl.gov/research/projects/waggle/downloads/datasets/#{&1}.complete.recent.tar"))
      |> Enum.map(&NodeMonitor.Utils.download!/1)

    csv_paths =
      tarball_paths
      |> Enum.map(&deflate_tarball/1)

    csv_paths
    |> Enum.each(fn path ->
      Logger.info("Ripping #{path}")
      path
      |> File.stream!()
      |> CSV.parse_stream()
      |> Stream.map(fn [node_id ,_ ,vsn ,address ,lat ,lon ,description ,start_ts ,end_ts] ->
        lat = parse_lonlat(lat)
        lon = parse_lonlat(lon)
        start_timestamp = parse_awful_timestamp(start_ts)
        end_timestamp = parse_awful_timestamp(end_ts)

        case Repo.get(Node, node_id) do
          nil ->
            %Node{id: node_id}
            |> Node.changeset(%{
              vsn: vsn,
              address: address,
              lon: lon,
              lat: lat,
              description: description,
              start_timestamp: start_timestamp,
              end_timestamp: end_timestamp
            })
            |> Repo.insert!()

          node ->
            node
            |> Node.changeset(%{
              vsn: vsn,
              address: address,
              lon: lon,
              lat: lat,
              description: description,
              start_timestamp: start_timestamp,
              end_timestamp: end_timestamp
            })
            |> Repo.update!()
        end
      end)
      |> Stream.run()
    end)

    tarball_paths
    |> Enum.each(&File.rm!/1)

    csv_paths
    |> Enum.map(&Path.dirname/1)
    |> Enum.each(&File.rm_rf!/1)
  end

  # helpers

  defp deflate_tarball(path) do
    parent_dirname = Path.dirname(path)

    # decompress the tarball
    Logger.info("decompressing tarball #{path}")
    {_, 0} = System.cmd("tar", ["xf", path, "-C", parent_dirname])

    # get the path to the nodes csv
    {paths, 0} = System.cmd("tar", ["tf", path])
    Logger.debug("extracted paths: #{inspect(paths)}")

    ext_dirname =
      String.split(paths, "\n")
      |> List.first()
    ext_dirname = Path.join([parent_dirname, ext_dirname])
    Logger.debug("extracted dirname: #{ext_dirname}")

    {paths, 0} = System.cmd("ls", [ext_dirname])
    Logger.debug("ls ext dirname: #{inspect(paths)}")

    nodes_csv = Path.join([ext_dirname, "nodes.csv"])
    Logger.info("nodes csv path: #{nodes_csv}")

    nodes_csv
  end

  defp parse_awful_timestamp(""), do: nil
  defp parse_awful_timestamp(value), do: Timex.parse!(value, "%Y/%m/%d %H:%M:%S", :strftime)

  defp parse_lonlat("0.0"), do: nil
  defp parse_lonlat(value), do: value
end

lib/node_monitor_web/controllers/nodes_controller.ex
defmodule NodeMonitorWeb.NodesController do
  use NodeMonitorWeb, :controller
  require Logger
  import Ecto.Query
  alias NodeMonitor.{Repo, Nodes, BootEvents, DataLogs, StatusLogs}
  alias NodeMonitor.Nodes.Node
  alias NodeMonitor.BootEvents.{BootEvent, LatestBootEvent}
  alias NodeMonitor.DataLogs.{DataLog, LatestDataLog}
  alias NodeMonitor.StatusLogs.{StatusLog, LatestStatusLog}


  @doc false
  def overview(conn, _) do
    count_all_nodes =
      Nodes.list_nodes()
      |> Repo.all()
      |> Enum.count()

    # boot events
    too_many_reboots = BootEvents.detect_too_many_reboots()
    too_many_media_changes = BootEvents.detect_too_many_media_changes()
    no_boot_events = BootEvents.detect_no_boot_events()
    no_recent_boot_events = BootEvents.detect_no_recent_boot_events()

    # data logs
    too_few_sensors = DataLogs.detect_too_few_sensors()
    ratio_too_low = DataLogs.detect_ratio_too_low()
    not_enough_data = DataLogs.detect_not_enough_data()
    no_data_logs = DataLogs.detect_no_data_logs()
    no_recent_data_logs = DataLogs.detect_no_recent_data_logs()

    # status logs
    nc_time_drift = StatusLogs.detect_nc_time_drift()
    ep_time_drift = StatusLogs.detect_ep_time_drift()
    nc_uptime_too_short = StatusLogs.detect_nc_uptime_too_short()
    ep_uptime_too_short = StatusLogs.detect_ep_uptime_too_short()
    wm_uptime_too_short = StatusLogs.detect_wm_uptime_too_short()
    cs_uptime_too_short = StatusLogs.detect_cs_uptime_too_short()
    bcam_uptime_too_short = StatusLogs.detect_bcam_uptime_too_short()
    tcam_uptime_too_short = StatusLogs.detect_tcam_uptime_too_short()
    mic_uptime_too_short = StatusLogs.detect_mic_uptime_too_short()
    no_status_logs = StatusLogs.detect_no_status_logs()
    no_recent_status_logs = StatusLogs.detect_no_recent_status_logs()

    render conn, "overview.html",
      count_all_nodes: count_all_nodes,
      too_many_reboots: too_many_reboots,
      too_many_media_changes: too_many_media_changes,
      no_boot_events: no_boot_events,
      no_recent_boot_events: no_recent_boot_events,
      too_few_sensors: too_few_sensors,
      ratio_too_low: ratio_too_low,
      not_enough_data: not_enough_data,
      no_data_logs: no_data_logs,
      no_recent_data_logs: no_recent_data_logs,
      nc_time_drift: nc_time_drift,
      ep_time_drift: ep_time_drift,
      nc_uptime_too_short: nc_uptime_too_short,
      ep_uptime_too_short: ep_uptime_too_short,
      wm_uptime_too_short: wm_uptime_too_short,
      cs_uptime_too_short: cs_uptime_too_short,
      bcam_uptime_too_short: bcam_uptime_too_short,
      tcam_uptime_too_short: tcam_uptime_too_short,
      mic_uptime_too_short: mic_uptime_too_short,
      no_status_logs: no_status_logs,
      no_recent_status_logs: no_recent_status_logs
  end

  @doc false
  def all_nodes(conn, _) do
    %Postgrex.Result{columns: cols, rows: rows} =
      Repo.query! """
      SELECT
        n.id, n.vsn, n.address, n.lat, n.lon, n.description,
        b.timestamp bts, d.timestamp dts, s.timestamp sts
      FROM nodes n
        LEFT JOIN latest_boot_events b ON n.id = b.node_id
        LEFT JOIN latest_data_logs d ON n.id = d.node_id
        LEFT JOIN latest_status_logs s ON n.id = s.node_id
      WHERE
        n.end_timestamp IS NULL
      ORDER BY n.vsn ASC
      """

    cols =
      cols
      |> Enum.map(&String.to_atom/1)

    nodes =
      rows
      |> Enum.map(& Enum.zip(cols, &1))
      |> Enum.map(& Enum.into(&1, %{}))

    count = Enum.count(nodes)

    render conn, "index.html",
      nodes: nodes,
      count: count
  end

  @doc false
  def map(conn, _) do
    all_nodes =
      Nodes.list_nodes()
      |> Repo.all()

    # boot events
    no_recent_boot_events = BootEvents.detect_no_recent_boot_events() |> MapSet.new()

    # data logs
    too_few_sensors = DataLogs.detect_too_few_sensors() |> Enum.map(&Tuple.to_list/1) |> Enum.map(& Enum.at(&1, 0)) |> MapSet.new()

    # status logs
    nc_time_drift = StatusLogs.detect_nc_time_drift() |> Enum.map(&Tuple.to_list/1) |> Enum.map(& Enum.at(&1, 0)) |> MapSet.new()
    ep_time_drift = StatusLogs.detect_ep_time_drift() |> Enum.map(&Tuple.to_list/1) |> Enum.map(& Enum.at(&1, 0)) |> MapSet.new()
    bcam_uptime_too_short = StatusLogs.detect_bcam_uptime_too_short() |> Enum.map(&Tuple.to_list/1) |> Enum.map(& Enum.at(&1, 0)) |> MapSet.new()
    tcam_uptime_too_short = StatusLogs.detect_tcam_uptime_too_short() |> Enum.map(&Tuple.to_list/1) |> Enum.map(& Enum.at(&1, 0)) |> MapSet.new()
    mic_uptime_too_short = StatusLogs.detect_mic_uptime_too_short() |> Enum.map(&Tuple.to_list/1) |> Enum.map(& Enum.at(&1, 0)) |> MapSet.new()

    nodes =
      all_nodes
      |> Enum.map(fn node ->
        {score, missing_boot_events?} =
          if MapSet.member?(no_recent_boot_events, node.id) do
            {1, true}
          else
            {0, false}
          end

        {score, missing_sensors?} =
          if MapSet.member?(too_few_sensors, node.id) do
            {score + 1, true}
          else
            {score, false}
          end

        {score, nc_drift?} =
          if MapSet.member?(nc_time_drift, node.id) do
            {score + 1, true}
          else
            {score, false}
          end

        {score, ep_drift?} =
          if MapSet.member?(ep_time_drift, node.id) do
            {score + 1, true}
          else
            {score, false}
          end

        {score, no_bcam?} =
          if MapSet.member?(bcam_uptime_too_short, node.id) do
            {score + 1, true}
          else
            {score, false}
          end

        {score, no_tcam?} =
          if MapSet.member?(tcam_uptime_too_short, node.id) do
            {score + 1, true}
          else
            {score, false}
          end

        {score, no_mic?} =
          if MapSet.member?(mic_uptime_too_short, node.id) do
            {score + 1, true}
          else
            {score, false}
          end

        color =
          cond do
            score >= 5 -> "red"
            score >= 4 -> "orange"
            score >= 3 -> "yellow"
            score >= 2 -> "blue"
            true -> "green"
          end

        Logger.debug("#{node.id} #{score} #{color}")

        %{
          type: "Feature",
          geometry: %{
            type: "Point",
            coordinates: [node.lon, node.lat]
          },
          properties: %{
            # node metadata
            id: node.id,
            vsn: node.vsn,
            address: node.address,
            description: node.description,
            # computed qualities
            missing_boot_info: missing_boot_events?,
            missing_sensors: missing_sensors?,
            nc_drift: nc_drift?,
            ep_drift: ep_drift?,
            no_bcam: no_bcam?,
            no_tcam: no_tcam?,
            no_mic: no_mic?,
            # pin color
            color: color
          }
        }
      end)
      |> Jason.encode!()

    render conn, "map.html",
      nodes: nodes
  end

  @doc false
  def show(conn, %{"id" => id}) do
    node = Repo.get!(Node, id)

    # data logs
    latest_data_log =
      (from l in LatestDataLog)
      |> where([l], l.node_id == ^id)
      |> Repo.one()

    data_logs =
      (from l in DataLog)
      |> where([l], l.node_id == ^id)
      |> order_by([asc: :timestamp])
      |> Repo.all()

    data_log_labels =
      data_logs
      |> Enum.map(& &1.timestamp)
      |> Enum.map(&NaiveDateTime.to_string/1)
      |> Jason.encode!()

    data_log_sensors =
      data_logs
      |> Enum.map(& &1.data_unique_sensors)
      |> Jason.encode!()

    data_log_ratio =
      data_logs
      |> Enum.map(& &1.data_valid_ratio)
      |> Jason.encode!()

    data_log_valid =
      data_logs
      |> Enum.map(& &1.data_valid_total)
      |> Jason.encode!()

    data_log_data =
      data_logs
      |> Enum.map(& &1.data_total)
      |> Jason.encode!()

    # status logs
    latest_status_log =
      (from l in LatestStatusLog)
      |> where([l], l.node_id == ^id)
      |> Repo.one()

    status_logs =
      (from l in StatusLog)
      |> where([l], l.node_id == ^id)
      |> order_by([asc: :timestamp])
      |> Repo.all()

    status_log_labels =
      status_logs
      |> Enum.map(& &1.timestamp)
      |> Enum.map(&NaiveDateTime.to_string/1)
      |> Jason.encode!()

    nc_uptime =
      status_logs
      |> Enum.map(& &1.up_nc_sys)
      |> Jason.encode!()

    ep_uptime =
      status_logs
      |> Enum.map(& &1.up_ep_sys)
      |> Jason.encode!()

    wm_uptime =
      status_logs
      |> Enum.map(& &1.up_wm_sys)
      |> Jason.encode!()

    cs_uptime =
      status_logs
      |> Enum.map(& &1.up_nc_cs)
      |> Jason.encode!()

    bcam_uptime =
      status_logs
      |> Enum.map(& &1.up_ep_bcam)
      |> Jason.encode!()

    tcam_uptime =
      status_logs
      |> Enum.map(& &1.up_ep_tcam)
      |> Jason.encode!()

    mic_uptime =
      status_logs
      |> Enum.map(& &1.up_ep_mic)
      |> Jason.encode!()

    nc_fail_counts =
      status_logs
      |> Enum.map(& &1.fc_nc)
      |> Jason.encode!()

    ep_fail_counts =
      status_logs
      |> Enum.map(& &1.fc_ep)
      |> Jason.encode!()

    cs_fail_counts =
      status_logs
      |> Enum.map(& &1.fc_cs)
      |> Jason.encode!()

    nc_current_usage =
      status_logs
      |> Enum.map(& &1.cu_nc)
      |> Jason.encode!()

    ep_current_usage =
      status_logs
      |> Enum.map(& &1.cu_ep)
      |> Jason.encode!()

    wm_current_usage =
      status_logs
      |> Enum.map(& &1.cu_wm)
      |> Jason.encode!()

    cs_current_usage =
      status_logs
      |> Enum.map(& &1.cu_cs)
      |> Jason.encode!()

    nc_rabbitmq =
      status_logs
      |> Enum.map(fn l ->
        case l.run_nc_rabbitmq do
          true -> 1
          false -> 0
          _ -> nil
        end
      end)
      |> Jason.encode!()

    ep_rabbitmq =
      status_logs
      |> Enum.map(fn l ->
        case l.run_ep_rabbitmq do
          true -> 1
          false -> 0

lib/node_monitor_web/views/nodes_view.ex
defmodule NodeMonitorWeb.NodesView do
  use NodeMonitorWeb, :view
end

lib/node_monitor_web/templates/nodes/index.html.eex
<h1><%= @count %> Nodes</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>VSN</th>
      <th>Address</th>
      <th>Location</th>
      <th>Description</th>
      <th>Latest Boot Timestamp</th>
      <th>Latest Data Log Timestamp</th>
      <th>Latest Status Log Timestamp</th>
    </tr>
  </thead>
  <tbody>
    <%= for n <- @nodes do %>
    <tr>
      <td><a href="<%= Routes.nodes_path(@conn, :show, n.id) %>"><%= n.id %></a></td>
      <td><%= n.vsn %></td>
      <td><%= n.address %></td>
      <td><%= n.lon %>, <%= n.lat %></td>
      <td><%= n.description %></td>
      <td><%= fmt_time n.bts %></td>
      <td><%= fmt_time n.dts %></td>
      <td><%= fmt_time n.sts %></td>
    </tr>
    <% end %>
  </tbody>
</table>

lib/node_monitor_web/templates/nodes/map.html.eex
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==" crossorigin="" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js" integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA==" crossorigin=""></script>

<style>
html, body, main, #map{
  height: 100%;
  width: 100%;
}
</style>

<div id="map"></div>

<script>
let myMap = L.map('map');

L.tileLayer(
  'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
  attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
  maxZoom: 18,
  id: 'mapbox.dark',
  accessToken: 'pk.eyJ1IjoidmZvcmdpb25lLXVjY2QiLCJhIjoiY2pwbHEwbHFwMDMyOTQ0cmczNnB2OTF0byJ9.GoxEA4ZXPQlHU25TPi54vA'
}).addTo(myMap);

let dataLayer = L.geoJson(<%= raw @nodes %>, {
  // instead of using markers, which are static images in leaflet, we're going
  // to conver the points to layers so we can idicate them with circle
  // markers. this allows us to style them -- essentially color code them for
  // easier visual grepping of system status.
  pointToLayer: function (f, latlon) {
    let mrkr = L.circleMarker(latlon, { radius: 6, weight: 1, opacity: 1, fillOpacity: 0.6 });
    return mrkr;
  },
  // this sets the style of the circle marker
  style: function (f) {
    switch (f.properties.color) {
      case 'red': return { color: '#ff0014' };
      case 'orange': return { color: '#ff7b0a' };
      case 'yellow': return { color: '#f0ff0a' };
      case 'blue': return { color: '#004ff0' };
      case 'green': return { color: '#14ff24' };
    }
  },
  // this is where we process each feature: set up popup text, update the
  // status counts, etc.
  onEachFeature: function (f, featureLayer) {
    // setup the popup text for each marker's onClick event
    let popup = `
    <table style="line-height:0.7em;">
      <tr>
        <th>ID</th>
        <td>${f.properties.id}</td>
      </tr>
      <tr>
        <th>VSN</th>
        <td>${f.properties.vsn}</td>
      </tr>
      <tr>
        <th>Location</th>
        <td>${f.geometry.coordinates}</td>
      </tr>
      <tr>
        <th>Address</th>
        <td>${f.properties.address}</td>
      </tr>
      <tr>
        <th>Description</th>
        <td>${f.properties.description}</td>
      </tr>
      <tr>
        <th>Missing Boot Events</th>
        <td>${f.properties.missing_boot_info}</td>
      </tr>
      <tr>
        <th>Missing Sensors</th>
        <td>${f.properties.missing_sensors}</td>
      </tr>
      <tr>
        <th>NC Time Drift</th>
        <td>${f.properties.nc_drift}</td>
      </tr>
      <tr>
        <th>EP Time Drift</th>
        <td>${f.properties.ep_drift}</td>
      </tr>
      <tr>
        <th>Missing BCam</th>
        <td>${f.properties.no_bcam}</td>
      </tr>
      <tr>
        <th>Missing TCam</th>
        <td>${f.properties.no_tcam}</td>
      </tr>
      <tr>
        <th>Missing Mic</th>
        <td>${f.properties.no_mic}</td>
      </tr>
    </table>

    <a href="/nodes/${f.properties.id}" target="_blank">Go to details page</a>
    `;
    // bind the text
    featureLayer.bindPopup(popup);
  }
}).addTo(myMap);

// recenter map
myMap.fitBounds(dataLayer.getBounds());
</script>

lib/node_monitor_web/templates/nodes/overview.html.eex
<h1>Node Overview</h1>

<p>
  <%= @count_all_nodes %> live nodes
</p>

<hr>

<h2>Boot Events</h2>

<ul>
  <li>
    <%= Enum.count(@too_many_reboots) %> nodes have rebooted more than once in the last 4 hours 
    <br><%= for {node_id, _} <- @too_many_reboots do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@too_many_media_changes) %> nodes have changed their boot media more than twice in the last 4 hours 
    <br><%= for {node_id, _, _} <- @too_many_media_changes do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@no_recent_boot_events) %> nodes have not sent a boot record (http event) in the last 4 hours 
    <br><%= for node_id <- @no_recent_boot_events do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@no_boot_events) %> nodes have never sent a boot record (http event) 
    <br><%= for node_id <- @no_boot_events do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
</ul>

<hr>

<h2>Data Quality Logs</h2>

<ul>
  <li>
    <%= Enum.count(@too_few_sensors) %> nodes have reported less than 14 sensors at least 12 times (totalling an hour) in the last 4 hours 
    <br><%= for {node_id, _} <- @too_few_sensors do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@ratio_too_low) %> nodes have reported a valid data ratio less than 80% at least 12 times (totalling an hour) in the last 4 hours 
    <br><%= for {node_id, _} <- @ratio_too_low do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@not_enough_data) %> nodes have not reported a sufficient total amount of data at least 12 times (totalling an hour) in the last 4 hours 
    <br><%= for {node_id, _} <- @not_enough_data do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@no_recent_data_logs) %> nodes have not had a data log computed in the last 4 hours
    <br><%= for node_id <- @no_recent_data_logs do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@no_data_logs) %> nodes have never had a data log computed
    <br><%= for node_id <- @no_data_logs do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
</ul>

<hr>

<h2>Status Logs</h2>

<ul>
  <li>
    <%= Enum.count(@nc_time_drift) %> nodes have a node controller whose epoch is off by at least 1 minute 
    <br><%= for {node_id, _} <- @nc_time_drift do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@ep_time_drift) %> nodes have an edge processor whose epoch is off by at least 1 minute 
    <br><%= for {node_id, _} <- @ep_time_drift do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@nc_uptime_too_short) %> nodes have a node controller with a reported uptime being less than 5 minutes at least once in the last 4 hours 
    <br><%= for {node_id, _} <- @nc_uptime_too_short do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@ep_uptime_too_short) %> nodes have an edge processor with a reported uptime being less than 5 minutes at least once in the last 4 hours
    <br><%= for {node_id, _} <- @ep_uptime_too_short do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@wm_uptime_too_short) %> nodes have a wagman with a reported uptime being less than 5 minutes at least once in the last 4 hours
    <br><%= for {node_id, _} <- @wm_uptime_too_short do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@cs_uptime_too_short) %> nodes have a coresense with a reported uptime being less than 5 minutes at least once in the last 4 hours
    <br><%= for {node_id, _} <- @cs_uptime_too_short do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@bcam_uptime_too_short) %> nodes have a bottom camera with a reported uptime being less than 5 minutes at least once in the last 4 hours
    <br><%= for {node_id, _} <- @bcam_uptime_too_short do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@tcam_uptime_too_short) %> nodes have a top camera with a reported uptime being less than 5 minutes at least once in the last 4 hours
    <br><%= for {node_id, _} <- @tcam_uptime_too_short do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@mic_uptime_too_short) %> nodes have a microphone with a reported uptime being less than 5 minutes at least once in the last 4 hours
    <br><%= for {node_id, _} <- @mic_uptime_too_short do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@no_recent_status_logs) %> nodes have not had a status log computed in the last 4 hours 
    <br><%= for node_id <- @no_recent_status_logs do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
  <li>
    <%= Enum.count(@no_status_logs) %> nodes have never had a status log computed 
    <br><%= for node_id <- @no_status_logs do %><a href="<%= Routes.nodes_path(@conn, :show, node_id) %>"><%= node_id %></a>, <% end %>
  </li>
</ul>